# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: armz/node-8.7.0-awscli

    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: aws s3 sync ./build s3://asciify.galaxiaskyklos.com --delete

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
